var emojiMap = {
    0: { emoji: '🌑', name: 'New Moon' },
    1: { emoji: '🏠', name: 'House' },
    2: { emoji: '🚗', name: 'Car' },
    3: { emoji: '✈️', name: 'Airplane' },
    4: { emoji: '🛳', name: 'Cruise Ship' },
    5: { emoji: '🚌', name: 'Bus' },
    6: { emoji: '🏫', name: 'School' },
    7: { emoji: '🏥', name: 'Hospital' },
    8: { emoji: '🗼', name: 'Tokyo Tower' },
    9: { emoji: '🗽', name: 'Statue of Liberty' },
    10: { emoji: '🎡', name: 'Ferris Wheel' },
    11: { emoji: '🎢', name: 'Roller Coaster' },
    12: { emoji: '🪑', name: 'Chair' },
    13: { emoji: '🛏', name: 'Bed' },
    14: { emoji: '💻', name: 'Laptop' },
    15: { emoji: '🖨', name: 'Printer' },
    16: { emoji: '🖱', name: 'Computer Mouse' },
    17: { emoji: '💽', name: 'Floppy Disk' },
    18: { emoji: '📸', name: 'Camera' },
    19: { emoji: '📺', name: 'Television' },
    20: { emoji: '📞', name: 'Telephone' },
    21: { emoji: '💡', name: 'Light Bulb' },
    22: { emoji: '🔦', name: 'Flashlight' },
    23: { emoji: '🗑', name: 'Wastebasket' },
    24: { emoji: '🧻', name: 'Toilet Paper' },
    25: { emoji: '🧼', name: 'Soap' },
    26: { emoji: '🧴', name: 'Lotion' },
    27: { emoji: '🪒', name: 'Razor' },
    28: { emoji: '🧹', name: 'Broom' },
    29: { emoji: '🎈', name: 'Balloon' },
    30: { emoji: '🎁', name: 'Wrapped Gift' },
    31: { emoji: '🎃', name: 'Jack-o-Lantern' },
    32: { emoji: '🎄', name: 'Christmas Tree' },
    33: { emoji: '🧩', name: 'Puzzle Piece' },
    34: { emoji: '🧸', name: 'Teddy Bear' },
    35: { emoji: '🪄', name: 'Magic Wand' },
    36: { emoji: '🎮', name: 'Video Game' },
    37: { emoji: '🎲', name: 'Dice' },
    38: { emoji: '🎰', name: 'Slot Machine' },
    39: { emoji: '🪅', name: 'Piñata' },
    40: { emoji: '🪆', name: 'Nesting Dolls' },
    41: { emoji: '🪡', name: 'Sewing Needle' },
    42: { emoji: '🧶', name: 'Yarn' },
    43: { emoji: '🏥', name: 'Hospital' },
    44: { emoji: '🏦', name: 'Bank' },
    45: { emoji: '🏭', name: 'Factory' },
    46: { emoji: '🏰', name: 'Castle' },
    47: { emoji: '🗿', name: 'Moai' },
    48: { emoji: '🎡', name: 'Ferris Wheel' },
    49: { emoji: '🎢', name: 'Roller Coaster' },
    50: { emoji: '💈', name: 'Barber Pole' },
    51: { emoji: '🎪', name: 'Circus Tent' },
    52: { emoji: '🎭', name: 'Performing Arts' },
    53: { emoji: '🎨', name: 'Artist Palette' },
    54: { emoji: '🧵', name: 'Thread' },
    55: { emoji: '🧶', name: 'Yarn' },
    56: { emoji: '👓', name: 'Glasses' },
    57: { emoji: '👕', name: 'T-Shirt' },
    58: { emoji: '👖', name: 'Jeans' },
    59: { emoji: '🧣', name: 'Scarf' },
    60: { emoji: '🧤', name: 'Gloves' },
    61: { emoji: '🧥', name: 'Coat' },
    62: { emoji: '🧦', name: 'Socks' },
    63: { emoji: '👗', name: 'Dress' },
    64: { emoji: '🩲', name: 'Briefs' },
    65: { emoji: '👙', name: 'Bikini' },
    66: { emoji: '👛', name: 'Purse' },
    67: { emoji: '👜', name: 'Handbag' },
    68: { emoji: '🎒', name: 'Backpack' },
    69: { emoji: '👞', name: 'Mans Shoe' },
    70: { emoji: '👑', name: 'Crown' },
    71: { emoji: '🎩', name: "Top Hat" },
    72: { emoji: '🎓', name: 'Graduation Cap' },
    73: { emoji: '🧢', name: 'Baseball Cap' },
    74: { emoji: '💄', name: 'Lipstick' },
    75: { emoji: '💍', name: 'Ring' }
}